language: python

python: 3.6

cache:
  pip: true

install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

script:
  - pylint process_kml
  - pycodestyle process_kml
