#! /usr/bin/env python
"""
Process an KML file downloaded from Google Maps Engine Lite and process it to
use on Maverick by:
- Download images and place then in a 'photo' directory
"""

from __future__ import absolute_import, print_function

import argparse
import os
import urllib
from pykml import parser as kml_parser


def get_parsed_file(filename):
    """
    Return a parsed file
    """
    return kml_parser.parse(open(filename, 'r')).getroot()


def check_for_dir(path):
    """
    Check  if the given path exists, otherwise, create it
    """
    if not os.path.exists(path):
        os.makedirs(path)

    return path


def download_pic(url, img_name, dest_dir='photos'):
    """
    Download an image from the given url and store it on the specified dir
    """
    if ' ' in url:
        url = url.split(' ')[0]

    if '?' in url:
        # Lets assume it's 'jpg'
        extension = 'jpg'
    else:
        extension = url.split('.')[-1]

    filename = '{0}.{1}'.format(img_name.encode('utf8'), extension)
    filename = os.path.join(dest_dir, filename)

    # If the file already exists, don't download it again
    if not os.path.isfile((filename)):
        print('Downloading: {0}'.format(url))
        urllib.urlretrieve(url, filename)


def parse_args():
    """Parse arguments from command line."""

    parser = argparse.ArgumentParser(
        description='Download images referenced in a KML file',
    )

    parser.add_argument(
        'input_files',
        nargs='+',
        default='',
        help='Path to files to process',
    )

    args = parser.parse_args()

    return args


def main():
    """
    Main application
    """

    args = parse_args()

    for filepath in args.input_files:
        filepath = os.path.abspath(filepath)
        filename = os.path.basename(filepath)

        if filename[-4:].lower() != '.kml':
            print('Invalid file type. Skipping.')
            continue

        name = filename[:-4]
        path = os.path.join(os.path.dirname(filepath), name)

        doc = get_parsed_file(filepath)

        print('Downloading pictures for {0}'.format(filepath))

        photos_dir = check_for_dir(os.path.join(path, 'photos'))

        for placemark in doc.Document.Folder.Placemark:
            try:
                name = placemark.name.text
                url = placemark.ExtendedData.Data.value.text

                print('{0}'.format(name.encode('utf8')))
                download_pic(url, name, photos_dir)
            except AttributeError:
                pass


if __name__ == "__main__":
    main()
